#!/bin/bash

# SPDX-License-Identifier: MPL-2.0
#
# Copyright (C) 2025 Aleksa Radomirovic
#
# This script is licensed under the Mozilla Public License Version 2.0.
# See LICENSE.txt for more information.

if [[ -z ${1} ]]; then
    echo "${0} error: no server folder given!"
    exit -1
fi

LOC=$(dirname ${0})
SAV=${LOC}/servers/${1}
DIR=$(mktemp -d)

if ! rsync -rtv ${SAV}/ ${DIR}; then
    rm -r ${DIR}
    exit -1
fi

if ! SERVER_JAR=$(find ${DIR} -maxdepth 1 -type f -iname "*.jar" | head -n 1); then
    rm -r ${DIR}
    exit -1
fi

SERVER_JAR=$(realpath --relative-to=${DIR} ${SERVER_JAR})
#echo "${SERVER_JAR}"

while true; do
    if ! docker container run --interactive --tty --rm \
            --volume ${DIR}:/mnt/server --publish 25565:25565 \
            --user minecraft --workdir /mnt/server \
            --name minecraft_${1} minecraft \
            java -Xmx12G -jar ${SERVER_JAR} --nogui; then
        rm -r ${DIR}
        exit -1
    fi

    rsync -rtuv ${DIR}/ ${SAV}

    echo
    read -p "Terminate? [y/N] " -t 15 USERCMD || { echo; continue; }
    case ${USERCMD} in
        [Yy]* ) break;;
    esac
done

rm -r ${DIR}
