#!/bin/bash

# SPDX-License-Identifier: MPL-2.0
#
# Copyright (C) 2025 Aleksa Radomirovic
#
# This script is licensed under the Mozilla Public License Version 2.0.
# See LICENSE.txt for more information.

PORT=25565

while [[ ${#} -gt 0 ]]; do
    case ${1} in
        -p|--port)
            PORT=${2}
            shift 2
            ;;
        * )
            SAV=${1}
            shift 1
            ;;
    esac
done

if [[ -z ${SAV} ]]; then
    echo "No server folder declared"
    exit -1
fi

echo "Running on host port ${PORT}..."
echo "Loading server folder ${SAV}..."

NAME=$(basename $(realpath ${SAV}))
DIR=$(mktemp -d)

echo "Using host temporary directory ${DIR}..."

if ! rsync -rt ${SAV}/ ${DIR}; then
    rm -r ${DIR}
    exit -1
fi

if ! SERVER_JAR=$(find ${DIR} -maxdepth 1 -type f -iname "*.jar" | head -n 1); then
    rm -r ${DIR}
    exit -1
fi

SERVER_JAR=$(realpath --relative-to=${DIR} ${SERVER_JAR})
#echo "${SERVER_JAR}"

if [[ -z ${TZ} ]]; then
    if [[ -f /etc/timezone ]]; then
        TZ=$(cat /etc/timezone)
    else
        TZ=UTC
    fi
fi

while true; do
    if ! docker container run --interactive --tty --rm \
            --volume ${DIR}:/mnt/server --publish ${PORT}:25565 \
            --user minecraft --workdir /mnt/server --env TZ=${TZ} \
            --name minecraft_${NAME} minecraft \
            java -Xmx12G -jar ${SERVER_JAR} --nogui; then
        rm -r ${DIR}
        exit -1
    fi

    rsync -rtu ${DIR}/ ${SAV}

    echo
    read -p "Terminate? [y/N] " -t 15 USERCMD || { echo; continue; }
    case ${USERCMD} in
        [Yy]* ) break;;
    esac
done

rm -r ${DIR}
